version: '3.7'

services:
  server-hub-api:
    build: ./api
    container_name: server-hub-api
    environment:
    - DB_HOST=postgres
    - DB_PORT=5432
    - DB_USERNAME=root
    - DB_PASSWORD=password
    - DB_DATABASE=root
    ports:
      - "8000:8000"

  postgres:
    container_name: server-hub-postgresdb
    image: postgres:10.5
    restart: on-failure
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=db_user
      - APP_DB_PASS=password
      - APP_DB_NAME=root
    ports:
      - 5432:5432

  pgadmin:
    container_name: server-hub-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: on-failure

volumes:
    postgres:
    pgadmin: